name: medicine_notification_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  #notification  
  timezone: ^0.10.1  
  flutter_local_notifications: ^19.3.0

  #db
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  
  #state management
  provider: ^6.1.5
  flutter_timezone: ^4.1.1
  flutter_tts: ^4.2.3
  shimmer: ^3.0.0
  android_notification_icons: ^0.0.1

assets:
  - assets/notification/noti.png
dev_dependencies:
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/notification/noti.png"
  android_12: true


  
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  android_notification_icons:

android_notification_icons:
  image_path: assets/notification/noti.png



flutter:
  uses-material-design: true
